### ISSUE TITLE
US 01.01.01 Entrant - Join a waiting list for an event with QR Code

### ISSUE THREAD

**Issue by Chathila** [CMPUT301F24tigers/tigers-lottery#10]
US 01.01.01 As an entrant, I want to join the waiting list for a specific event 

![Image](https://github.com/user-attachments/assets/48af022e-9139-4422-969a-f1eedb695828)

The QR code does not need to functional for this part, just create a space for the camera feed to appear

**Comment by anhuynh1234** [comment]
Move to final checkpoint as we are not doing any qr code for this part
