### ISSUE TITLE
SETUP - Create Entrant Dashboard

### ISSUE THREAD

**Issue by AbhroChowdhury** [CMPUT301F24tigers/tigers-lottery#64]
Create the entrant dashboard as per FIGMA. As part of this story, the layout should be created, as well as the necessary backend components (ArrayAdapters for the ListView, Count of events, Button)

![Image](https://github.com/user-attachments/assets/4b0722d3-36cc-4b66-8bf8-bfe6d1dde672)

**Comment by Chathila** [comment]
Looks like An is still working on this
